version: '3.9'

services:
  app:
    container_name: api-nestjs
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app
    command: bash -c "npm install && npm run build && npm run start:dev"
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: db-api-nestjs
    image: postgres
    tty: true
    environment:
      POSTGRES_DB: api-nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: